[build]
  publish = "public"              # folder static untuk HTML, CSS, JS
  functions = "netlify/functions" # folder fungsi serverless

[functions]
  directory = "netlify/functions"

# redirect opsional: hanya kalau mau custom route
[[redirects]]
  from = "/note"
  to = "/.netlify/functions/note"
  status = 200
