[build]
  publish = "public"          # folder static files (index.html, css, js)
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200
